apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out .\dj
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: web
  type: LoadBalancer